[general]
import = ["~/.alacritty/solarized_dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10

[font.normal]
family = "MesloLGM Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "tmux"

[window]
opacity = 1

[terminal]
